# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 17:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('complemento', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Autenticacao',
            new_name='Cliente',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='login',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='senha',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='endereco',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='autenticacao.Cliente'),
        ),
    ]
