# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_cliente_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=16)),
                ('cod_seg', models.CharField(max_length=3)),
                ('data_vencimento', models.CharField(max_length=7)),
                ('nome', models.CharField(max_length=100)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartoes', to='autenticacao.Cliente')),
            ],
        ),
    ]
