# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_pedido',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
