# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20161111_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='valor_pedido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tiporoupa',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tiporoupa',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Camisa'), (2, 'Camiseta/Blusa'), (3, 'Edredon'), (4, 'Lencol'), (5, 'Roupa de Luxo'), (6, 'Roupa Intima'), (7, 'Roupa Jeans'), (8, 'Toalha de Banho'), (9, 'Toalha de Mesa'), (10, 'Toalha de Rosto')], default=2),
        ),
    ]
