# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20161112_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporoupa',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
