# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0004_cartao'),
        ('pedido', '0006_auto_20161125_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to='autenticacao.Cliente'),
            preserve_default=False,
        ),
    ]
