# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 21:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_auto_20161126_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default='User.id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to='autenticacao.Cliente'),
        ),
    ]
