# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 22:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_auto_20161129_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(default=datetime.datetime(2016, 12, 1, 19, 2, 46, 660395)),
        ),
    ]
