# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 17:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_auto_20161201_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_entrega',
            field=models.DateField(default=datetime.datetime(2016, 12, 3, 14, 0, 21, 524453)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(default='User.id', on_delete=django.db.models.deletion.CASCADE, related_name='usuario_pedido', to='autenticacao.Cliente'),
        ),
    ]
